services: # definisce servizi
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped  #se termina inaspettatamente, definisce quando fare restart (sempre  ameno che non venga chiusa)
    ports:
      - '3000:3000'
    volumes: # dove salvare affinch√© sopravviva al container
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning # Optional: for provisioning
    #environment:
    #  - GF_INSTALL_PLUGINS=grafana-infinity-datasource # Install the Infinity plugin
volumes:
  grafana-storage: {}