global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "fastapi_hf"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          #- "host.docker.internal:8000"
          - "lucabadiali-ml-ops-project.hf.space:443"