global:
  scrape_interval: 30s   # più gentile verso HF

scrape_configs:
  - job_name: "fastapi_hf"
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          #- "host.docker.internal:8000"
          - "lucabadiali-ml-ops-project.hf.space:443"
    # Se la Space è privata, aggiungi:
    # authorization:
    #   type: Bearer
    #   credentials: "hf_XXXXXXXXXXXX"   # token read-only
