name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main          # or your default branch
  workflow_dispatch:  # allow manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_HUB_TOKEN }}
        run: |
          # just for debugging; you can remove once it works
          git remote -v

          # push current commit on main to the Space's main branch
          git push --force \
            https://__token__:${HF_TOKEN}@huggingface.co/spaces/lucabadiali/ML_OPS_Project \
            HEAD:main
